### **Used Car Price Prediction**

1. Problem Statement
    - This dataset contains used cars sold on cardekho.com in India as well as important features of these cars
    - If user can predict the price of the car based on the input features
    - Prediction results can be used to give new seller the price suggestion based on market condition

2. Data Collection
    - The dataset is collected from scrapping from cardekho website
    - The data consists of 13 column and 15411 rows.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv("cardekho_imputated.csv",index_col=0)
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
# Data Cleaning
# Check Missing Values
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [ ]:
# There are no missing values
df.info()

<class 'pandas.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  str
 1   brand              15411 non-null  str
 2   model              15411 non-null  str
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  str
 6   fuel_type          15411 non-null  str
 7   transmission_type  15411 non-null  str
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), str(6)
memory usage: 1.6 MB

In [7]:
## Lets check for duplicate record
df[df.duplicated()]

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
261,Honda City,Honda,City,8,70000,Individual,Petrol,Manual,16.80,1497,116.30,5,545000
462,Maruti Baleno,Maruti,Baleno,2,5000,Individual,Petrol,Automatic,21.40,1197,83.10,5,686000
1739,Maruti Swift Dzire,Maruti,Swift Dzire,4,50000,Individual,Diesel,Manual,28.40,1248,74.02,5,680000
1838,Maruti Wagon R,Maruti,Wagon R,13,100000,Individual,Petrol,Manual,18.90,1061,67.00,5,150000
1907,Hyundai i20,Hyundai,i20,3,50000,Individual,Petrol,Manual,18.60,1197,81.83,5,625000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19311,Maruti Swift,Maruti,Swift,8,80000,Individual,Diesel,Manual,22.90,1248,74.00,5,350000
19434,Maruti Wagon R,Maruti,Wagon R,6,50000,Individual,CNG,Manual,26.60,998,58.16,5,450000
19489,Tata Tiago,Tata,Tiago,4,30000,Individual,Petrol,Manual,23.84,1199,84.00,5,350000
19505,Hyundai Grand,Hyundai,Grand,6,30000,Individual,Petrol,Manual,18.90,1197,82.00,5,450000
19521,Land Rover Rover,Land Rover,Rover,5,128000,Dealer,Diesel,Automatic,12.63,2179,147.50,5,2675000

In [8]:
# Drop duplicates
df.drop_duplicates(keep="first",inplace=True)

In [9]:
## Lets check for duplicate record
df[df.duplicated()]

Empty DataFrame
Columns: [car_name, brand, model, vehicle_age, km_driven, seller_type, fuel_type, transmission_type, mileage, engine, max_power, seats, selling_price]
Index: []

In [10]:
# CarName, Brand, Model -- are similar
# We will consider only model and drop Carname and brand
df.drop(columns=["car_name","brand"],inplace=True)

In [11]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [ ]:
## Check values distribution for categorical values
df["model"].value_counts() ##There are 120 Models in this category

model
i20             898
Swift Dzire     875
Swift           774
Alto            768
City            750
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [13]:
df["seller_type"].value_counts()

seller_type
Dealer              9459
Individual          5612
Trustmark Dealer     173
Name: count, dtype: int64

In [14]:
df["fuel_type"].value_counts()

fuel_type
Petrol      7555
Diesel      7342
CNG          299
LPG           44
Electric       4
Name: count, dtype: int64

In [15]:
df["transmission_type"].value_counts()

transmission_type
Manual       12094
Automatic     3150
Name: count, dtype: int64

In [ ]:
df["model"].unique() # Label Encoding Preffered here since 120 categories are there

<StringArray>
[        'Alto',        'Grand',          'i20',     'Ecosport',
      'Wagon R',          'i10',        'Venue',        'Swift',
        'Verna',       'Duster',
 ...
     'Panamera',      'Alturas',       'Altroz',           'NX',
     'Carnival',            'C',           'RX',        'Ghost',
 'Quattroporte',       'Gurkha']
Length: 120, dtype: str

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 15244 entries, 0 to 19543
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15244 non-null  str
 1   vehicle_age        15244 non-null  int64
 2   km_driven          15244 non-null  int64
 3   seller_type        15244 non-null  str
 4   fuel_type          15244 non-null  str
 5   transmission_type  15244 non-null  str
 6   mileage            15244 non-null  float64
 7   engine             15244 non-null  int64
 8   max_power          15244 non-null  float64
 9   seats              15244 non-null  int64
 10  selling_price      15244 non-null  int64
dtypes: float64(2), int64(5), str(4)
memory usage: 1.4 MB

In [22]:
## Check Numerical Features
num_features=[feature for feature in df.columns if df[feature].dtype!="string"]
print(f"{num_features = }")
## Check Categorical Features
cat_features=[feature for feature in df.columns if feature not in num_features]
print(f"{cat_features = }")
## Check Discrete Features
discrete=[feature for feature in df.columns if len(df[feature].unique())<=25]
print(f"{discrete = }")
## Check Continous Features
continous=[feature for feature in df.columns if len(df[feature].unique())>=25]
print(f"{continous = }")

num_features = ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']
cat_features = ['model', 'seller_type', 'fuel_type', 'transmission_type']
discrete = ['vehicle_age', 'seller_type', 'fuel_type', 'transmission_type', 'seats']
continous = ['model', 'km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [ ]:
# We will apply 
# Label Encoding for model
# OneHotEncoding for seller_type
# OneHotEncoding for fuel_type
# OneHotEncoding for transmission_type

In [23]:
## Divide Independent and Dependent Features
X=df.drop(columns=["selling_price"])
y=df["selling_price"]

In [ ]:
## Feature Encoding and Scaling

In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X["model"]=le.fit_transform(X["model"])

In [25]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [33]:
## Create Column Transformer for 3 Types of Transformer
onehot_columns=X.select_dtypes(include="string").columns
print(onehot_columns) ## Will take the latest categorical/string columns for OHE
# num_features=onehot_columns=X.select_dtypes(exclude="string").columns
# print(num_features)
## Since I do not need to apply StandardScaler on label encoded or discrete numerical features -- So I will only take continous numerical features
num_features=[feature for feature in X.columns[1:] if len(df[feature].unique())>=25]
print(num_features)

Index(['seller_type', 'fuel_type', 'transmission_type'], dtype='str')
['km_driven', 'mileage', 'engine', 'max_power']

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
transform=[
    ("OneHotEncoding",OneHotEncoder(drop="first"),onehot_columns),
    ("StandardScaler",StandardScaler(),num_features)
]
ct=ColumnTransformer(transform,remainder='passthrough')

In [36]:
X=ct.fit_transform(X)

In [39]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.243329,0.000640,-1.326227,-1.265491,7.0,9.0,5.0
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.688493,-0.191245,-0.555669,-0.433600,54.0,5.0,5.0
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.084236,-0.646971,-0.555669,-0.480205,118.0,11.0,5.0
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.360084,0.293264,-0.938066,-0.780804,7.0,9.0,5.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.495311,0.736997,0.022729,-0.047016,38.0,6.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15239,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.867708,0.027024,-0.768966,-0.758667,117.0,9.0,5.0
15240,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.727130,-0.527043,-0.217469,-0.221550,42.0,2.0,7.0
15241,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.219463,0.346032,0.022729,0.067864,77.0,6.0,5.0
15242,0.0,0.0,1.0,0.0,0.0,0.0,1.0,72.334381,-0.886827,1.331332,0.917931,114.0,5.0,7.0
15243,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.823721,-0.407115,0.020808,0.395960,25.0,2.0,5.0

In [40]:
ct.get_feature_names_out()

array(['OneHotEncoding__seller_type_Individual',
       'OneHotEncoding__seller_type_Trustmark Dealer',
       'OneHotEncoding__fuel_type_Diesel',
       'OneHotEncoding__fuel_type_Electric',
       'OneHotEncoding__fuel_type_LPG',
       'OneHotEncoding__fuel_type_Petrol',
       'OneHotEncoding__transmission_type_Manual',
       'StandardScaler__km_driven', 'StandardScaler__mileage',
       'StandardScaler__engine', 'StandardScaler__max_power',
       'remainder__model', 'remainder__vehicle_age', 'remainder__seats'],
      dtype=object)

In [41]:
## Train, Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((12195, 14), (3049, 14), (12195,), (3049,))

In [45]:
## Model Training
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [46]:
## Create a Function to Evaluate Model
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=root_mean_squared_error(true,predicted)
    r2=r2_score(true,predicted)
    return mae,rmse,r2

In [48]:
## Model Training
models={
    "Linear Regression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "KNeighborsRegressor":KNeighborsRegressor(),
    "DecisionTreeRegressor":DecisionTreeRegressor(),
    "RandomForestRegressor":RandomForestRegressor()
}


for k,v in models.items():
    # Train Model
    v.fit(X_train,y_train)

    # Make predictions
    y_train_pred=v.predict(X_train)
    y_test_pred=v.predict(X_test)

    # Performance Check
    print(k)
    print("-"*30)
    print(evaluate_model(y_train,y_train_pred))
    print(evaluate_model(y_test,y_test_pred))
    print("\n")

Linear Regression
------------------------------
(275284.3899581517, 566013.4712838263, 0.6224216387180521)
(262717.1886108095, 446765.18534247123, 0.6717231990253707)


Lasso
------------------------------
(275282.697443001, 566013.4773502352, 0.622421630624447)
(262720.22961661394, 446764.7313976301, 0.6717238661296547)


Ridge
------------------------------
(275249.68342744064, 566013.9203616474, 0.6224210395728245)
(262723.3408841826, 446758.2508972233, 0.671733389612778)


KNeighborsRegressor
------------------------------
(82703.63673636736, 288782.767171647, 0.9017129932648859)
(96354.66546408659, 200618.45208266922, 0.9338052879661191)


DecisionTreeRegressor
------------------------------
(4798.996856635234, 19681.921172661907, 0.9995434497991564)
(129603.41095441129, 325362.11588492844, 0.8258932878977858)


RandomForestRegressor
------------------------------
(40186.234879288626, 128435.82604538558, 0.9805586719521523)
(103888.74397410285, 303761.9146828599, 0.8482431896086661)

In [50]:
## Initialize parameter for Hyperparameter Tuning for both KNearestNeighbour and RandomForestRegressor
knn_param={
    "n_neighbors":[2,3,10,20,40,50]
}
rf_params={
    "n_estimators":[100,200,500,1000],
    "criterion":["squared_error", "absolute_error", "poisson"],
    "max_depth":[5,8,10,15,"None"],
    "min_samples_split":[2,8,15,20],
    "max_features":[5,7,"auto",8]
}

In [51]:
# Model List for Hyperparameter Tuning
randomcv_models=[
    ("KNeighboursRegressor",KNeighborsRegressor(),knn_param),
    ("RandomForestRegressor",RandomForestRegressor(),rf_params)
]

In [52]:
from sklearn.model_selection import RandomizedSearchCV
model_param={}
for name,model,param in randomcv_models:
    random=RandomizedSearchCV(estimator=model,param_distributions=param,n_iter=100,cv=3,verbose=2,n_jobs=-1)
    random.fit(X_train,y_train)
    model_param[name]=random.best_params_

for model,param in model_param.items():
    print(model,param,"\n")

Fitting 3 folds for each of 6 candidates, totalling 18 fits
[CV] END ......................................n_neighbors=2; total time=   0.0s
[CV] END ......................................n_neighbors=2; total time=   0.0s
[CV] END ......................................n_neighbors=2; total time=   0.0s
[CV] END ......................................n_neighbors=3; total time=   0.0s
[CV] END ......................................n_neighbors=3; total time=   0.0s
[CV] END ......................................n_neighbors=3; total time=   0.0s
[CV] END .....................................n_neighbors=10; total time=   0.0s
[CV] END .....................................n_neighbors=10; total time=   0.0s
[CV] END .....................................n_neighbors=10; total time=   0.0s
[CV] END .....................................n_neighbors=20; total time=   0.0s
[CV] END .....................................n_neighbors=20; total time=   0.0s
[CV] END .....................................n_neighbors=20; total time=   0.0s
[CV] END .....................................n_neighbors=40; total time=   0.0s
[CV] END .....................................n_neighbors=40; total time=   0.0s
[CV] END .....................................n_neighbors=40; total time=   0.0s
[CV] END .....................................n_neighbors=50; total time=   0.0s
[CV] END .....................................n_neighbors=50; total time=   0.0s
[CV] END .....................................n_neighbors=50; total time=   0.0s
Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END criterion=absolute_error, max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END criterion=poisson, max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   2.4s
[CV] END criterion=poisson, max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   2.4s
[CV] END criterion=poisson, max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   2.4s
[CV] END criterion=absolute_error, max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=  13.5s
[CV] END criterion=absolute_error, max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=  13.5s
[CV] END criterion=absolute_error, max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=  13.5s
[CV] END criterion=poisson, max_depth=None, max_features=8, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END criterion=poisson, max_depth=None, max_features=8, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END criterion=poisson, max_depth=None, max_features=8, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END criterion=squared_error, max_depth=8, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END criterion=squared_error, max_depth=8, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END criterion=squared_error, max_depth=8, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END criterion=poisson, max_depth=8, max_features=5, min_samples_split=15, n_estimators=1000; total time=   7.2s
[CV] END criterion=poisson, max_depth=8, max_features=5, min_samples_split=15, n_estimators=1000; total time=   7.2s
[CV] END criterion=poisson, max_depth=8, max_features=5, min_samples_split=15, n_estimators=1000; total time=   7.2s
[CV] END criterion=absolute_error, max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   5.2s
[CV] END criterion=absolute_error, max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   5.2s
[CV] END criterion=absolute_error, max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   5.2s
[CV] END criterion=absolute_error, max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=  54.9s
[CV] END criterion=absolute_error, max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=  54.9s
[CV] END criterion=absolute_error, max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=  55.0s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END criterion=squared_error, max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   1.6s
[CV] END criterion=squared_error, max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   1.6s
[CV] END criterion=squared_error, max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   1.6s
[CV] END criterion=squared_error, max_depth=8, max_features=8, min_samples_split=15, n_estimators=500; total time=   3.0s
[CV] END criterion=squared_error, max_depth=8, max_features=8, min_samples_split=15, n_estimators=500; total time=   3.0s
[CV] END criterion=squared_error, max_depth=8, max_features=8, min_samples_split=15, n_estimators=500; total time=   3.0s
[CV] END criterion=squared_error, max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END criterion=squared_error, max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END criterion=squared_error, max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END criterion=squared_error, max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END criterion=squared_error, max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END criterion=squared_error, max_depth=10, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, max_depth=8, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END criterion=squared_error, max_depth=8, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END criterion=squared_error, max_depth=8, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=  12.9s
[CV] END criterion=absolute_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=  12.9s
[CV] END criterion=absolute_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=  12.9s
[CV] END criterion=squared_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   3.7s
[CV] END criterion=squared_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   3.7s
[CV] END criterion=squared_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=500; total time=   3.7s
[CV] END criterion=absolute_error, max_depth=None, max_features=7, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=None, max_features=7, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=None, max_features=7, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END criterion=poisson, max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END criterion=poisson, max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.0s
[CV] END criterion=poisson, max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END criterion=absolute_error, max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=  27.8s
[CV] END criterion=absolute_error, max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=  27.7s
[CV] END criterion=absolute_error, max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=  27.8s
[CV] END criterion=squared_error, max_depth=10, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.6s
[CV] END criterion=squared_error, max_depth=10, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.6s
[CV] END criterion=squared_error, max_depth=10, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.6s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=15, n_estimators=200; total time=   7.8s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=15, n_estimators=200; total time=   7.8s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=15, n_estimators=200; total time=   7.8s
[CV] END criterion=poisson, max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  10.8s
[CV] END criterion=poisson, max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  10.7s
[CV] END criterion=poisson, max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  11.2s
[CV] END criterion=absolute_error, max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=15, n_estimators=1000; total time=   6.5s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=15, n_estimators=1000; total time=   6.2s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=15, n_estimators=1000; total time=   6.4s
[CV] END criterion=absolute_error, max_depth=5, max_features=5, min_samples_split=15, n_estimators=100; total time=   2.8s
[CV] END criterion=absolute_error, max_depth=5, max_features=5, min_samples_split=15, n_estimators=100; total time=   2.7s
[CV] END criterion=absolute_error, max_depth=5, max_features=5, min_samples_split=15, n_estimators=100; total time=   2.8s
[CV] END criterion=poisson, max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  11.1s
[CV] END criterion=poisson, max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  10.9s
[CV] END criterion=poisson, max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  11.1s
[CV] END criterion=squared_error, max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END criterion=poisson, max_depth=15, max_features=8, min_samples_split=20, n_estimators=500; total time=   6.7s
[CV] END criterion=poisson, max_depth=15, max_features=8, min_samples_split=20, n_estimators=500; total time=   6.6s
[CV] END criterion=poisson, max_depth=15, max_features=8, min_samples_split=20, n_estimators=500; total time=   6.5s
[CV] END criterion=squared_error, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.5s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.5s
[CV] END criterion=poisson, max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.5s
[CV] END criterion=squared_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.5s
[CV] END criterion=squared_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.5s
[CV] END criterion=squared_error, max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.5s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=8, n_estimators=200; total time=   8.0s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=8, n_estimators=200; total time=   7.9s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=8, n_estimators=200; total time=   8.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END criterion=poisson, max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END criterion=poisson, max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END criterion=poisson, max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END criterion=poisson, max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END criterion=poisson, max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END criterion=poisson, max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   4.0s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   3.9s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=20, n_estimators=100; total time=   4.0s
[CV] END criterion=poisson, max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   2.6s
[CV] END criterion=poisson, max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   2.6s
[CV] END criterion=poisson, max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   2.5s
[CV] END criterion=poisson, max_depth=None, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END criterion=poisson, max_depth=None, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END criterion=poisson, max_depth=None, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END criterion=squared_error, max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=   8.3s
[CV] END criterion=squared_error, max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=   8.6s
[CV] END criterion=squared_error, max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=   8.8s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=20, n_estimators=1000; total time=  40.2s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=20, n_estimators=1000; total time=  39.4s
[CV] END criterion=absolute_error, max_depth=8, max_features=5, min_samples_split=20, n_estimators=1000; total time=  39.2s
[CV] END criterion=squared_error, max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   1.6s
[CV] END criterion=squared_error, max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   1.6s
[CV] END criterion=squared_error, max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   1.6s
[CV] END criterion=poisson, max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END criterion=poisson, max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END criterion=poisson, max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END criterion=squared_error, max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END criterion=squared_error, max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END criterion=squared_error, max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END criterion=absolute_error, max_depth=10, max_features=8, min_samples_split=20, n_estimators=500; total time=  33.4s
[CV] END criterion=absolute_error, max_depth=10, max_features=8, min_samples_split=20, n_estimators=500; total time= 1.1min
[CV] END criterion=absolute_error, max_depth=10, max_features=8, min_samples_split=20, n_estimators=500; total time=  31.7s
[CV] END criterion=poisson, max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END criterion=poisson, max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END criterion=poisson, max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END criterion=squared_error, max_depth=None, max_features=5, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END criterion=poisson, max_depth=8, max_features=7, min_samples_split=8, n_estimators=200; total time=   1.7s

In [59]:
## Model Training
models={
    "KNeighborsRegressor":KNeighborsRegressor(n_neighbors=4,n_jobs=-1),
    "RandomForestRegressor":RandomForestRegressor(n_estimators=200, min_samples_split=2, max_features=8, max_depth=15, criterion="absolute_error",n_jobs=-1)
}


for k,v in models.items():
    # Train Model
    v.fit(X_train,y_train)

    # Make predictions
    y_train_pred=v.predict(X_train)
    y_test_pred=v.predict(X_test)

    # Performance Check
    print(k)
    print("-"*30)
    print(evaluate_model(y_train,y_train_pred))
    print(evaluate_model(y_test,y_test_pred))
    print("\n")

KNeighborsRegressor
------------------------------
(78166.07472324723, 263048.2217824297, 0.9184499366848078)
(94872.98089537553, 189312.57236826938, 0.9410558838168506)


RandomForestRegressor
------------------------------
(54787.6921894219, 140010.28150962546, 0.9768967318081464)
(98193.75789193177, 227385.2221479143, 0.914963374179333)