**Used Car Prediction**
1. Problem Statement
    - This dataset contains used cars sold on cardekho.com in India as well as important features of these cars
    - If user can predict the price of the car based on the input features
    - Prediction results can be used to give new seller the price suggestion based on market condition

2. Data Collection
    - The dataset is collected from scrapping from cardekho website
    - The data consists of 13 column and 15411 rows.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("cardekho_imputated.csv",index_col=0)
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [3]:
## Data Cleaning
df.columns

Index(['car_name', 'brand', 'model', 'vehicle_age', 'km_driven', 'seller_type',
       'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power',
       'seats', 'selling_price'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  str
 1   brand              15411 non-null  str
 2   model              15411 non-null  str
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  str
 6   fuel_type          15411 non-null  str
 7   transmission_type  15411 non-null  str
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), str(6)
memory usage: 1.6 MB

In [5]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [6]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [11]:
## No missing values
## Checking the duplicate records and dropping them
df[df.duplicated()]

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
261,Honda City,Honda,City,8,70000,Individual,Petrol,Manual,16.80,1497,116.30,5,545000
462,Maruti Baleno,Maruti,Baleno,2,5000,Individual,Petrol,Automatic,21.40,1197,83.10,5,686000
1739,Maruti Swift Dzire,Maruti,Swift Dzire,4,50000,Individual,Diesel,Manual,28.40,1248,74.02,5,680000
1838,Maruti Wagon R,Maruti,Wagon R,13,100000,Individual,Petrol,Manual,18.90,1061,67.00,5,150000
1907,Hyundai i20,Hyundai,i20,3,50000,Individual,Petrol,Manual,18.60,1197,81.83,5,625000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19311,Maruti Swift,Maruti,Swift,8,80000,Individual,Diesel,Manual,22.90,1248,74.00,5,350000
19434,Maruti Wagon R,Maruti,Wagon R,6,50000,Individual,CNG,Manual,26.60,998,58.16,5,450000
19489,Tata Tiago,Tata,Tiago,4,30000,Individual,Petrol,Manual,23.84,1199,84.00,5,350000
19505,Hyundai Grand,Hyundai,Grand,6,30000,Individual,Petrol,Manual,18.90,1197,82.00,5,450000
19521,Land Rover Rover,Land Rover,Rover,5,128000,Dealer,Diesel,Automatic,12.63,2179,147.50,5,2675000

In [12]:
df.drop_duplicates(keep='first',inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 15244 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15244 non-null  str
 1   brand              15244 non-null  str
 2   model              15244 non-null  str
 3   vehicle_age        15244 non-null  int64
 4   km_driven          15244 non-null  int64
 5   seller_type        15244 non-null  str
 6   fuel_type          15244 non-null  str
 7   transmission_type  15244 non-null  str
 8   mileage            15244 non-null  float64
 9   engine             15244 non-null  int64
 10  max_power          15244 non-null  float64
 11  seats              15244 non-null  int64
 12  selling_price      15244 non-null  int64
dtypes: float64(2), int64(5), str(6)
memory usage: 1.6 MB

In [14]:
# segregating the numerical, categorical, discrete and continous columns
cat_feature=[feature for feature in df.columns if df[feature].dtype == "string"]
print(cat_feature)

['car_name', 'brand', 'model', 'seller_type', 'fuel_type', 'transmission_type']

In [15]:
num_feature = [feature for feature in df.columns if feature not in cat_feature]
print(num_feature)

['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']

In [19]:
num_discrete_feature=[feature for feature in num_feature if len(df[feature].unique())<=25]
print(num_discrete_feature)

['vehicle_age', 'seats']

In [20]:
cat_discrete_feature=[feature for feature in cat_feature if len(df[feature].unique())<=25]
print(cat_discrete_feature)

['seller_type', 'fuel_type', 'transmission_type']

In [22]:
continous_feature=[feature for feature in df.columns if len(df[feature].unique())>=25]
print(continous_feature)

['car_name', 'brand', 'model', 'km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [23]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [25]:
## We do not need car name or brand, model signifies the details
df.drop(columns=["car_name","brand"],inplace=True)

In [26]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [27]:
## Checking the values for discrete categorical values
for feature in cat_discrete_feature:
    print(df[feature].value_counts())

seller_type
Dealer              9459
Individual          5612
Trustmark Dealer     173
Name: count, dtype: int64
fuel_type
Petrol      7555
Diesel      7342
CNG          299
LPG           44
Electric       4
Name: count, dtype: int64
transmission_type
Manual       12094
Automatic     3150
Name: count, dtype: int64

In [ ]:
## We will not transform the discrete numerical features 'vehicle_age', 'seats'
## Standard Scale 'km_driven', 'mileage', 'engine', 'max_power'
## OneHotEncode 'seller_type', 'fuel_type', 'transmission_type'
## LabelEncode 'model'

In [29]:
# Lets first define the dependent and independent features and split the dataset
X=df.iloc[:,:-1]
y=df["selling_price"]

In [38]:
X

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [31]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
19537     250000
19540     925000
19541     425000
19542    1225000
19543    1200000
Name: selling_price, Length: 15244, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [39]:
X_train.shape,X_test.shape

((11433, 14), (3811, 14))

In [33]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
le=LabelEncoder()
X_train["model"]=le.fit_transform(X_train["model"])
X_test["model"]=le.transform(X_test["model"])
ss_features=['km_driven', 'mileage', 'engine', 'max_power']
ohe_features=['seller_type', 'fuel_type', 'transmission_type']
transformer=[
    ("StandardScaler",StandardScaler(),ss_features),
    ("OneHotEncoder",OneHotEncoder(drop="first"),ohe_features)
]

ct=ColumnTransformer(transformers=transformer,remainder='passthrough',n_jobs=-1,verbose=True)

In [34]:
X_train=ct.fit_transform(X_train)
X_test=ct.transform(X_test)

In [35]:
ct.get_feature_names_out()

array(['StandardScaler__km_driven', 'StandardScaler__mileage',
       'StandardScaler__engine', 'StandardScaler__max_power',
       'OneHotEncoder__seller_type_Individual',
       'OneHotEncoder__seller_type_Trustmark Dealer',
       'OneHotEncoder__fuel_type_Diesel',
       'OneHotEncoder__fuel_type_Electric',
       'OneHotEncoder__fuel_type_LPG', 'OneHotEncoder__fuel_type_Petrol',
       'OneHotEncoder__transmission_type_Manual', 'remainder__model',
       'remainder__vehicle_age', 'remainder__seats'], dtype=object)

In [37]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-0.660378,-1.125062,0.217769,0.077142,1.0,0.0,0.0,0.0,0.0,1.0,1.0,95.0,9.0,5.0
1,-0.833825,-0.535667,-0.548799,-0.272576,1.0,0.0,0.0,0.0,0.0,1.0,1.0,99.0,4.0,5.0
2,-0.378298,1.577529,0.025647,-0.151231,0.0,0.0,1.0,0.0,0.0,0.0,1.0,24.0,3.0,5.0
3,0.142480,0.266964,-0.552641,-0.403075,0.0,0.0,0.0,0.0,0.0,1.0,1.0,89.0,5.0,5.0
4,-0.651614,-1.045997,-0.554562,-0.641072,1.0,0.0,0.0,0.0,0.0,1.0,1.0,39.0,6.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11428,0.255797,-0.990891,-0.554562,-0.711015,1.0,0.0,0.0,0.0,0.0,1.0,1.0,44.0,7.0,5.0
11429,0.159225,-0.137946,1.939184,1.346926,0.0,0.0,0.0,0.0,0.0,1.0,0.0,20.0,6.0,5.0
11430,-0.504023,0.710208,-1.317288,-1.095471,0.0,0.0,0.0,0.0,0.0,1.0,1.0,78.0,4.0,5.0
11431,1.534918,-1.613829,2.886347,3.865368,0.0,0.0,1.0,0.0,0.0,0.0,0.0,36.0,9.0,5.0
11432,0.227372,-1.391009,2.826789,0.886893,0.0,0.0,1.0,0.0,0.0,0.0,1.0,83.0,9.0,7.0

In [40]:
## Model Training
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [41]:
## Create a Function to Evaluate Model
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=root_mean_squared_error(true,predicted)
    r2=r2_score(true,predicted)
    return mae,rmse,r2

In [42]:
## Model Training
models={
    "Linear Regression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "KNeighborsRegressor":KNeighborsRegressor(),
    "DecisionTreeRegressor":DecisionTreeRegressor(),
    "RandomForestRegressor":RandomForestRegressor(),
    "AdaBoostRegressor":AdaBoostRegressor()
}

for k,v in models.items():
    # Train Model
    v.fit(X_train,y_train)

    # Make predictions
    y_train_pred=v.predict(X_train)
    y_test_pred=v.predict(X_test)

    # Performance Check
    print(k)
    print("-"*30)
    print("Performance of Training Dataset : (mae,rmse,r2)")
    print(evaluate_model(y_train,y_train_pred))
    print("Performance of Test Dataset : (mae,rmse,r2)")
    print(evaluate_model(y_test,y_test_pred))
    print("\n")

Linear Regression
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(265814.2249821222, 556209.7473982351, 0.6146154709030278)
Performance of Test Dataset : (mae,rmse,r2)
(275591.2278970778, 503558.350383446, 0.6802126392330163)


Lasso
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(265812.8680416449, 556209.751470922, 0.6146154652592917)
Performance of Test Dataset : (mae,rmse,r2)
(275590.88740845857, 503558.7533909048, 0.6802121273688279)


Ridge
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(265778.13301859633, 556210.1821987435, 0.6146148683768928)
Performance of Test Dataset : (mae,rmse,r2)
(275563.8176125119, 503561.66375354084, 0.6802084308731986)


KNeighborsRegressor
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(81325.30394472143, 284195.463655113, 0.8993876325577846)
Performance of Test Dataset : (mae,rmse,r2)
(107174.10784570979, 292602.91656415287, 0.892026049395777)


DecisionTreeRegressor
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(4741.616373655209, 19357.775630501972, 0.9995332030723385)
Performance of Test Dataset : (mae,rmse,r2)
(132948.54587597307, 311719.4881222792, 0.8774566921373321)


RandomForestRegressor
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(39818.24848544752, 140340.23897611638, 0.9754652572425788)
Performance of Test Dataset : (mae,rmse,r2)
(106360.94078470294, 236734.6235979831, 0.9293218373648456)


AdaBoostRegressor
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(267483.2779156521, 407809.7726134926, 0.792827387288058)
Performance of Test Dataset : (mae,rmse,r2)
(278626.8256613412, 443286.7046663703, 0.7521829960509693)

In [43]:
## Initialize parameter for Hyperparameter Tuning for both KNearestNeighbour and RandomForestRegressor
knn_param={
    "n_neighbors":[2,3,10,20,40,50]
}
rf_params={
    "n_estimators":[100,200,500,1000],
    "criterion":["squared_error", "absolute_error", "poisson"],
    "max_depth":[5,8,10,15,"None"],
    "min_samples_split":[2,8,15,20],
    "max_features":[5,7,"auto",8]
}
ada_params={
    "n_estimators":[50,60,70,80,90,100],
    "loss":["linear", "square", "exponential"]
}

In [44]:
# Model List for Hyperparameter Tuning
randomcv_models=[
    ("KNeighboursRegressor",KNeighborsRegressor(),knn_param),
    ("RandomForestRegressor",RandomForestRegressor(),rf_params),
    ("AdaBoostRegressor",AdaBoostRegressor(),ada_params)
]

In [45]:
from sklearn.model_selection import RandomizedSearchCV
model_param={}
for name,model,param in randomcv_models:
    random=RandomizedSearchCV(estimator=model,param_distributions=param,n_iter=100,cv=3,verbose=2,n_jobs=-1)
    random.fit(X_train,y_train)
    model_param[name]=random.best_params_

for model,param in model_param.items():
    print(f"Best Parameter for {model} :")
    print(param)

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 18 candidates, totalling 54 fits
Best Parameter for KNeighboursRegressor :
{'n_neighbors': 2}
Best Parameter for RandomForestRegressor :
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 5, 'max_depth': 15, 'criterion': 'absolute_error'}
Best Parameter for AdaBoostRegressor :
{'n_estimators': 50, 'loss': 'linear'}

In [46]:
## Model Training
models={
    "KNeighborsRegressor":KNeighborsRegressor(n_neighbors=2,n_jobs=-1),
    "RandomForestRegressor":RandomForestRegressor(n_estimators=500, min_samples_split=2, max_features=5, max_depth=15, criterion="absolute_error",n_jobs=-1),
    "AdaboostRegressor":AdaBoostRegressor(n_estimators=50,loss="linear")
}

for k,v in models.items():
    # Train Model
    v.fit(X_train,y_train)

    # Make predictions
    y_train_pred=v.predict(X_train)
    y_test_pred=v.predict(X_test)

    # Performance Check
    print(k)
    print("-"*30)
    print("Performance of Training Dataset : (mae,rmse,r2)")
    print(evaluate_model(y_train,y_train_pred))
    print("Performance of Test Dataset : (mae,rmse,r2)")
    print(evaluate_model(y_test,y_test_pred))
    print("\n")

KNeighborsRegressor
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(57751.63998950407, 156622.35148835884, 0.9694420254033603)
Performance of Test Dataset : (mae,rmse,r2)
(110987.04408291787, 275091.64500263514, 0.9045630632917895)


RandomForestRegressor
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(55607.15665179743, 139622.2358420227, 0.9757156623883456)
Performance of Test Dataset : (mae,rmse,r2)
(101057.17160850171, 227795.25600639815, 0.9345588321388598)


AdaboostRegressor
------------------------------
Performance of Training Dataset : (mae,rmse,r2)
(254213.23826312617, 377959.91915433307, 0.8220456616112696)
Performance of Test Dataset : (mae,rmse,r2)
(263793.51688330836, 412338.9509865513, 0.7855774710519231)